help_plus = """
HERE IS HELP FOR BANCODES :-
✣ {Vx01} - SCAMMER.
✣ {Vx02} - COMMUNITY HATE.
✣ {Vx03} - ABUSE SPAM.
✣ {Vx04} - NSFW SPAMMER.
✣ {Vx05} - IMPERSONATION.
✣ {Vx06} - MD/BTC SCAM.
✣ {Vx07} - ADDING SPAMBOTS.
✣ {Vx08} - ILLEGAL.
✣ {Vx09} - PHISHING.
✣ {Vx10} - FRAUD PROMOTION  [ANY KIND].
✣ {Vx11} - CYBER THREATENING / CYBER BULLY.
✣ {Vx12} - CHILD ABUSE.
✣ {Vx13} - BAN EVASION.
✣ {Vx14} - SPAMBOT.
✣ {Vx15} - RAID INITIALIZOR. 
✣ {Vx16} - RAID PARTICIPANT.
✣ {Vx17} - KRIMINALANT.
✣ {Vx18} - RAID/SPAM INFLAMMER.
✣ {Vx-20} - RAID // SCAMMER BAN BY SCANNER BOT'S REPORTS
"""

__plugin_name__ = "Bancodes"
