help_plus = """
HERE IS HELP FOR BARCODES :-
✣ {SCx01} - SCAMMER.
✣ {SCx02} - SPAM ADDING MEMBER.
✣ {SCx03} - ABUSE SPAM.
✣ {SCx04} - NSFW SPAMMER.
✣ {SCx05} - IMPERSONATION.
✣ {SCx06} - MD/BTC SCAM.
✣ {SCx07} - ADDING SPAMBOTS.
✣ {SCx08} - ILLEGAL.
✣ {SCx09} - PHISHING.
✣ {SCx10} - FRAUD PROMOTION  [ANY KIND].
✣ {SCx11} - CYBER THREATENING / CYBER BULLY.
✣ {SCx12} - CHILD ABUSE.
✣ {SCx13} - BAN EVASION.
✣ {SCx14} - SPAMBOT.
✣ {SCx15} - RAID INITIALIZOR. 
✣ {SCx16} - RAID PARTICIPANT.
✣ {SCx17} - KRIMINALANT.
✣ {SCx18} - RAID/SPAM INFLAMMER.
✣ {SCx-20} - RAID // SCAMMER BAN BY SCANNER BOT'S REPORTS
"""

__plugin_name__ = "Bancodes"
